# Generated by Django 3.0.3 on 2020-02-19 02:50

import api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('flag', models.ImageField(null=True, upload_to='country_flags')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('currency_code', models.CharField(blank=True, choices=[('COP', 'Colombian Peso'), ('EUR', 'Euro'), ('USD', 'Dollar')], max_length=3)),
                ('flag', models.ImageField(null=True, upload_to='country_flags')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('flag', models.ImageField(null=True, upload_to='region_flags')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='api.Country')),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.ImageField(upload_to=api.models.flag_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_codes', to='api.City')),
            ],
        ),
        migrations.CreateModel(
            name='RegionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], max_length=2)),
                ('name', models.CharField(max_length=250)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_translations', to='api.Region')),
            ],
        ),
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], max_length=2)),
                ('name', models.CharField(max_length=250)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_translations', to='api.Country')),
            ],
        ),
        migrations.CreateModel(
            name='CityTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], max_length=2)),
                ('name', models.CharField(max_length=250)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_translations', to='api.City')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='api.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='api.Region'),
        ),
        migrations.AddConstraint(
            model_name='regiontranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'region'), name='unique_language_region'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('code', 'country'), name='unique_country_region'),
        ),
        migrations.AddConstraint(
            model_name='countrytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'country'), name='unique_language_country'),
        ),
        migrations.AddConstraint(
            model_name='citytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'city'), name='unique_language_city'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('code', 'country'), name='unique_country_city'),
        ),
    ]
