# Generated by Django 3.0.3 on 2020-02-19 03:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200219_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.flag_path),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.flag_path),
        ),
        migrations.AlterField(
            model_name='region',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.flag_path),
        ),
    ]
