# Generated by Django 3.0.3 on 2020-02-18 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200218_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='api.Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('iso_code', 'country'), name='unique_country_city'),
        ),
    ]
