# Generated by Django 3.0.3 on 2020-03-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200320_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='local_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='citytranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish')], max_length=2),
        ),
        migrations.AlterField(
            model_name='countrytranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish')], max_length=2),
        ),
        migrations.AlterField(
            model_name='regiontranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish')], max_length=2),
        ),
    ]
