# Generated by Django 3.0.3 on 2020-02-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200218_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
