# Generated by Django 3.0.3 on 2020-03-21 18:24

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_added_local_code_to_region'),
    ]

    operations = [
        UnaccentExtension()
    ]
