# Generated by Django 3.0.3 on 2020-02-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200218_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_codes', to='api.City'),
        ),
    ]
